package com.qilu.qilu.net;

public enum HttpMethod {
    GET,
    GET_NO_PARAMS,
    POST,
    POST_RAW,
    POST_FILE,
    POST_ASSESSMENT_WITH_PHOTOS,
    POST_REPAIR_ORDER_WITH_PHOTOS,
    POST_REPAIR_ORDER_WITH_ALL,
    POST_REPAIR_ORDER_WITH_VOICE,
    POST_REPAIR_ORDER_WITH_NONE,
    PUT,
    PUT_RAW,
    DELETE,
    UPLOAD
}
